#!/usr/bin/env python3
import socket, ssl
from bs4 import BeautifulSoup
import argparse
import json


# Headers to prevent getting the bot verification redirect
headers_get = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'DNT': '1',
    'Connection': 'close'
}


# Function to build the https request data
def build_headers(host, path):
    request_line = f"GET {path} HTTP/1.1\r\n"
    header_lines = f"Host: {host}\r\n"
    for key, value in headers_get.items():
        header_lines += f"{key}: {value}\r\n"
    header_lines += "\r\n"
    return request_line + header_lines


def send_https_request(host, path):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)   
    # Creating context to ensure compatibility with websites
    context = ssl.create_default_context()
    s_socket = context.wrap_socket(sock, server_hostname=host)
    
    try:
        # Connecting to the server on the https port
        s_socket.connect((host, 443))
        request = build_headers(host, path)
        s_socket.sendall(request.encode())
        
        # Receive the response in chunks
        response = b""
        while True:
            chunk = s_socket.recv(4096)
            if not chunk:
                break
            response += chunk
        
        response_str = response.decode('utf-8', errors='replace')
        # Split the response into headers and body
        header, _, body = response_str.partition("\r\n\r\n")
        
        return body, header
    finally:
        s_socket.close()

def return_help_info():
    # Return help info
    return "go2web -u <URL>         # make an HTTP request to the specified URL and print the response\ngo2web -s <search-term> # make an HTTP request to search the term using your favorite search engine and print top 10 results\ngo2web -h               # show this help"


# Function that will use duckduckgo html search to return page data
def send_web_engine_request(query):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s_socket = ssl.wrap_socket(sock)
    query = '+'.join(query.split())
    host = 'html.duckduckgo.com'
    path = '/html?q=' + query
    request_data = build_headers(host, path)
    
    try:
        s_socket.connect((host, 443))
        s_socket.sendall(request_data.encode())

        response = b""
        while True:
            chunk = s_socket.recv(4096)
            if not chunk:
                break
            response += chunk

        response_str = response.decode('utf-8', errors='replace')
        header, _, body = response_str.partition("\r\n\r\n")
    finally:
        s_socket.close()

    soup = BeautifulSoup(body, "html.parser")
    output = []

    # Scrape page data from html file 
    i = 1
    for result in soup.find_all('a', {'class': 'result__a'}):
        title = result.get_text(strip=True)
        url = result.get('href')
        output.append({f'title{i}': title, 'url': url})
        i += 1
        if i > 10:
            break

    return output


def parse_html(html_body):
    soup = BeautifulSoup(html_body, "html.parser")
    sections = {}
    
    title_tag = soup.find("title")
    if title_tag:
        sections["title"] = title_tag.get_text()

    i = 1
    for p in soup.find_all("p"):
        text = p.get_text()
        if text:
            sections[f"paragraph{i}"] = text
        i += 1
    
    return sections


# Function to accept json responses
def verify_content_type(body, headers):
    check_for_html = int(headers.find("text/html"))
    if check_for_html != -1:
        parsed_html = parse_html(body)
        print(parsed_html)

    else:
        try:
            parsed_json = json.loads(body)
            print(json.dumps(parsed_json, indent=2))
        except Exception as e:
            print("Error parsing JSON:", e)


# Function to implement caching of links with a dictionary
def get_cached_https_request(host, path):
    url = f"https://{host}{path}"
    try:
        with open("cache.json", 'r') as file:
                data = json.load(file)
    except:
        data = {}

    if url in data:
        return tuple(data[url])

    else:
        body, header = send_https_request(host, path)
        data[url] = [body, header]
        with open("cache.json", 'w') as file:
            json.dump(data, file)

        return body, header


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="go2web CLI", add_help=False)
    parser.add_argument("-h", action="store_true")
    parser.add_argument("-u")
    parser.add_argument("-s")

    args = parser.parse_args()

    if args.h:
        print("go2web -u <URL>         # make an HTTP request to the specified URL and print the response")
        print("go2web -s <search-term> # make an HTTP request to search the term using your favorite search engine and print top 10 results")
        print("go2web -h               # show this help")
    
    elif args.u:
        try:
            host, path = args.u.split("://")[-1].split("/", 1)
            path = "/" + path

            body, headers = get_cached_https_request(host, path)
            # body, headers = send_https_request(host, path)
            verify_content_type(body, headers)

        except Exception as e:
            print("Error occurred:", e)

    elif args.s:
        response = send_web_engine_request(args.s)
        print(response)

    else:
        print("Invalid command! Use 'go2web -h' to view available commands")

# https://api.github.com/